#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
pushd "$OPENSHIFT_REPO_DIR/plugins" > /dev/null
git clone https://github.com/koppen/redmine_github_hook.git
popd > /dev/null
