#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#
#  main(): Add a Gemfile.lock from the specific version and replace the env
#          variables for DB HOST, USERNAME and PASSWORD.
# 
pushd "$OPENSHIFT_REPO_DIR" > /dev/null
[ ! -f Gemfile.lock ] && cp -f "Gemfile.lock.ruby-$OPENSHIFT_RUBY_VERSION" Gemfile.lock
cp config/database.yml-$OPENSHIFT_RUBY_VERSION config/database.yml
popd > /dev/null

export OPENSHIFT_GIT_REPO_DIR="$OPENSHIFT_DATA_DIR/gitrepos/"
mkdir -p $OPENSHIFT_GIT_REPO_DIR

pushd "$OPENSHIFT_GIT_REPO_DIR" > /dev/null
git clone --mirror https://github.com/miurahr/swiftbook.git
cd swiftbook.git
git fetch -q --all -p
popd > /dev/null
